[package]
name = "encompute-backend"
description = "Backend trait and mock backend for Encompute"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
encompute-ir.workspace = true
encompute-ckks.workspace = true

[lints]
workspace = true
