#!/usr/bin/env bash
# Regenerate the hashed Python lock of a release from requirements-release.in
# (which includes deploy/confidential-space-training/requirements.txt).
#
#   scripts/release/lock-python.sh          # rewrite constraints.txt
#   scripts/release/lock-python.sh --check  # fail if it is out of date
#
# Needs uv (https://docs.astral.sh/uv/). Install with the lock:
#   pip install --require-hashes -r scripts/release/python/constraints.txt \
#     --extra-index-url https://download.pytorch.org/whl/cpu
set -euo pipefail
cd "$(dirname "$0")/python"
OUT="constraints.txt"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
uv pip compile requirements-release.in \
  --python-version 3.11 --python-platform x86_64-manylinux_2_28 \
  --extra-index-url https://download.pytorch.org/whl/cpu --index-strategy unsafe-best-match \
  --generate-hashes --no-header --quiet -o "$tmp"
{
  echo "# Generated by scripts/release/lock-python.sh from requirements-release.in."
  echo "# CPython 3.11, Linux x86_64. Do not edit by hand."
  cat "$tmp"
} > "$tmp.full"
if [ "${1:-}" = "--check" ]; then
  if diff -q "$tmp.full" "$OUT" >/dev/null; then echo "constraints.txt is up to date"; rm -f "$tmp.full"; exit 0; fi
  diff -u "$OUT" "$tmp.full" | head -40
  rm -f "$tmp.full"
  echo "constraints.txt is out of date: run scripts/release/lock-python.sh" >&2
  exit 1
fi
mv "$tmp.full" "$OUT"
echo "wrote scripts/release/python/$OUT ($(grep -cE '^[a-z]' "$OUT") packages)"
