[package]
name = "veil-cli"
description = "The veil command-line tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "veil"
path = "src/main.rs"

[dependencies]
veil-ir.workspace = true
veil-runtime.workspace = true
serde_json.workspace = true
clap = { version = "~4.5", features = ["derive"] }

[features]
openfhe = ["veil-runtime/openfhe"]

[lints]
workspace = true
