[package]
name = "veil-cli"
description = "The veil command-line tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "veil"
path = "src/main.rs"

[dependencies]
veil-runtime.workspace = true

[features]
openfhe = ["veil-runtime/openfhe"]

[lints]
workspace = true
