#!/usr/bin/env python3
"""Third-party notices for the Rust crates linked into Encompute's production
artifacts (the CLI, evaluator and control-plane binaries and the Python
extension, with the production features): every crate's license and notice
files, reproduced from its source as cargo fetched it.

    scripts/third_party_notices.py            # rewrite the generated part of THIRD_PARTY_NOTICES.md
    scripts/third_party_notices.py --check    # fail if it is out of date

Needs the crates' sources (`cargo fetch --locked`). The crate list is the
SBOM's (scripts/sbom.py: normal dependencies of the production roots, all
platforms). Identical license texts are printed once, with every crate that
ships them. A crate that ships no license file must offer Apache-2.0 (whose
text needs no per-crate copyright line and is reproduced from the crates that
ship it); it is listed as used under Apache-2.0, and any other crate without a
license file fails the script.
"""

import argparse
import os
import re
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sbom import FEATURES, PRODUCTION, cargo_graph  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NOTICES = os.path.join(ROOT, "THIRD_PARTY_NOTICES.md")
BEGIN = "<!-- BEGIN GENERATED BY scripts/third_party_notices.py: do not edit by hand -->"
END = "<!-- END GENERATED -->"
LICENSE_FILE = re.compile(r"^(licen[cs]e|copying|notice|copyright|unlicense)([-._].*)?$", re.I)


def license_files(pkg):
    """(relative path, text) of every license or notice file in the crate."""
    root = os.path.dirname(pkg["manifest_path"])
    out = []
    for dirpath, dirnames, files in os.walk(root):
        rel = os.path.relpath(dirpath, root)
        depth = 0 if rel == "." else rel.count(os.sep) + 1
        # The crate root, and license directories (LICENSES/, license/).
        dirnames[:] = [d for d in dirnames if depth == 0 and re.match(r"^licen[cs]es?$", d, re.I)]
        for f in sorted(files):
            if depth == 0 and not LICENSE_FILE.match(f):
                continue
            path = os.path.join(dirpath, f)
            try:
                with open(path, encoding="utf-8") as fh:
                    text = fh.read().strip()
            except (OSError, UnicodeDecodeError):
                continue
            if text:
                out.append((os.path.normpath(os.path.join(rel, f)), text))
    return sorted(out)


def generate():
    pkgs, _, _, seen = cargo_graph(PRODUCTION, FEATURES)
    third = [pkgs[i] for i in seen if pkgs[i].get("source") is not None]
    third.sort(key=lambda p: (p["name"], p["version"]))
    missing_sources = [p for p in third if not os.path.exists(p["manifest_path"])]
    if missing_sources:
        names = ", ".join(f"{p['name']} {p['version']}" for p in missing_sources[:10])
        raise SystemExit(f"crate sources not fetched (run cargo fetch --locked): {names}")
    texts = {}                        # text -> index
    users = defaultdict(list)         # index -> ["crate version (file)"]
    without = []
    for p in third:
        files = license_files(p)
        if not files:
            without.append(p)
        for rel, text in files:
            k = texts.setdefault(text, len(texts))
            users[k].append(f"{p['name']} {p['version']} ({rel})")
    lines = [
        BEGIN,
        "",
        "## Rust crates in the production binaries and the Python extension",
        "",
        f"{len(third)} crates from crates.io are compiled into the production artifacts",
        "(the dependency graph of `encompute-cli`, `encompute-evaluator`, `encompute-control`",
        "and `encompute-py` with the production features, the same list as the SBOM). Each",
        "is used under a permissive license (`deny.toml` admits no copyleft; where a crate",
        "offers a choice, a permissive one is used). Their licenses, as each crate ships",
        "them:",
        "",
        "| Crate | Version | License |",
        "|---|---|---|",
    ]
    for p in third:
        lines.append(f"| {p['name']} | {p['version']} | {p.get('license') or 'see its files'} |")
    lines += ["", "### License and notice texts", ""]
    for text, k in sorted(texts.items(), key=lambda x: x[1]):
        lines.append(f"#### {len(users[k])} file(s): " + ", ".join(users[k]))
        lines += ["", "```", text.replace("```", "'''"), "```", ""]
    if without:
        lines += [
            "### Crates that ship no license file",
            "",
            "These crates are used under Apache-2.0, one of the licenses their manifests",
            "offer; its text is reproduced above from the crates that ship it.",
            "",
        ]
        for p in without:
            lines.append(f"- {p['name']} {p['version']}: {p.get('license') or 'no license declared'}")
        lines.append("")
    lines += [
        "## Python packages",
        "",
        "The Python wheel bundles no Python package: its dependencies (numpy, and the",
        "optional torch, transformers, peft and their dependencies) are installed",
        "separately, each under its own license, recorded per release in the wheel's SBOM",
        "(`scripts/release/python_licenses.py`). The confidential training image installs",
        "them from `deploy/confidential-space-training/requirements.lock`; each package's",
        "license travels in its `*.dist-info` directory inside the image.",
        "",
        END,
    ]
    return "\n".join(lines) + "\n", without


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the notices are out of date")
    args = ap.parse_args()
    generated, without = generate()
    bad = [p["name"] for p in without
           if "Apache-2.0" not in re.split(r"[\s()/]+", p.get("license") or "")]
    if bad or (without and "Apache License" not in generated):
        raise SystemExit(f"crates with no license file that do not offer Apache-2.0: {bad}")
    with open(NOTICES, encoding="utf-8") as fh:
        current = fh.read()
    if BEGIN in current and END in current:
        head = current[: current.index(BEGIN)]
        tail = current[current.index(END) + len(END):].lstrip("\n")
    else:
        head, tail = current.rstrip("\n") + "\n\n", ""
    new = head + generated + (("\n" + tail) if tail else "")
    if args.check:
        if new != current:
            print("THIRD_PARTY_NOTICES.md is out of date: run scripts/third_party_notices.py",
                  file=sys.stderr)
            return 1
        print("THIRD_PARTY_NOTICES.md is up to date")
        return 0
    with open(NOTICES, "w", encoding="utf-8") as fh:
        fh.write(new)
    print(f"wrote THIRD_PARTY_NOTICES.md ({generated.count(chr(10))} generated lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
