[package]
name = "veil-runtime"
description = "Veil executor, differential testing and compiled artifacts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
veil-ir.workspace = true
veil-ckks.workspace = true
veil-backend.workspace = true
veil-openfhe = { workspace = true, optional = true }

[features]
openfhe = ["dep:veil-openfhe"]

[lints]
workspace = true
